### ISSUE TITLE
It's confusing when two or more auctions occur simultaneously.

### ISSUE THREAD

**Issue by Smithgift** [martinlsanchez/daiauctions#1]
This is pretty easy to see, at the time of this post there's two overlapping auctions in the last 3.14 days.

1. It would be great if you could tell them apart--possibly by different colors on the IDs? Actually, you could get away with just a few different shades (on the ID or on the line) for anything but a massive vault liquidation.

2. It would also be cool if you could tell whether it's two simultaneous but unrelated auctions or one vault that got bitten more than once.

**Comment by martinlsanchez** [comment]
Sry @Smithgift about the delay in the response. 

1. Yeah, I know that its hard to tell apart when two or more Auctions are happening at the same time. I working about some solutions, already tried some of your proposals but nothing really works (in my eyes at least, too much colors).... but something about that for sure it's gonna come soon. 

2. I tried to add the Vault number of the flip Auction, but the performance about that calculation it's soooo bad... but I'm trying new altenatives.

General thoughts.... there is a LOT to be done and to be improved but right now I'm putting there all the info about all Auctions variables.... as soon as I ended with that for sure a general re thinking of the desing is in the roadmap, lol.

I really really glad than you like it.

**Comment by Smithgift** [comment]
One brainstorm idea I had is to use symbols. For example, the first auction has a tiny circle next to its lines, the second has a bar, the third has a triangle, etc. A similar option would be to have a large selection of symbols, and always give a certain ID the same symbol. Then you just recycle them every hundred auctions or so.

**Comment by martinlsanchez** [comment]
Wow. I like that Idea a lot. You imagine it over the dotted line? or where?

The only thing is that I would like to use Unicode shapes (https://www.w3schools.com/charsets/ref_utf_geometric.asp) to make sure that doesn't hit much in performance but I think we have a lot to play with... :-)

**Comment by martinlsanchez** [comment]
I closed this issue by error. I reopen it to maybe the alternatives for this topic flowing... :-)
