### ISSUE TITLE
Bid data incorrect on Tend events

### ISSUE THREAD

**Issue by andy8052** [martinlsanchez/daiauctions#4]
`let raw = event.raw.data.slice(289, -248);` has previously worked fine because of the lot size being 50. With the new lot size being 500 an error is occurring because it is supposed to be `let raw = event.raw.data.slice(288, -248);`

**Comment by martinlsanchez** [comment]
Wow, nice catch man. You rock!

I would never imagine that the `lot` could end up needing that extra byte.

I Promise it's gonna be fixes in the next release.
